#!/bin/sh
export BOOTSTRAP_CUBE_MARKER=/run/cube_commit_done
export BOOTSTRAP_CUBE_MODE=/etc/appliance/state/boot_mode
export BOOTSTRAP_CUBE_LOG=/var/log/bootstrap_cube.log
source /usr/sbin/hex_tuning /etc/settings.txt
if [ "x$T_cubesys_control_hosts" = "x" ] ; then
    export MASTER_CONTROL=$T_cubesys_controller
    [ -n "$MASTER_CONTROL" ] || MASTER_CONTROL=$T_net_hostname
else
    export MASTER_CONTROL=$(echo $T_cubesys_control_hosts | cut -d"," -f1)
fi

export HOSTNAME=$(ssh localhost hostname 2>/dev/null)
query="insert system,category=BSP,severity=I,key=BSP00001I,service=bootstrap,host=$HOSTNAME"
# Bring up influxdb as early as possible to log bootstrap activities
cubectl node exec -r control -pn "systemctl show -p SubState influxdb | grep -q -i running || systemctl restart influxdb"
space_filler="                                                                                "
BootstrapAndClusterstart()
{
    if [ ! -e "$BOOTSTRAP_CUBE_MARKER" ] ; then
        msg="Bootstrapping CubeCOS"
        echo -n "$space_filler">$(hex_sdk GetKernelConsoleDevices) ; echo -n "$msg" $'\r' | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)
        hex_sdk influx_event "${query},severity=\"I\" message=\"$msg\""
        bash -c "hex_config -p bootstrap standalone-done | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)"
        if [ ! -e "$BOOTSTRAP_CUBE_MARKER" ] ; then
            msg="Bootstrap error: $(journalctl | grep hex | egrep -i 'failed to commit')"
            echo -n "$space_filler">$(hex_sdk GetKernelConsoleDevices) ; echo -n "$msg" $'\r' | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)
            hex_sdk influx_event "${query},severity=\"W\" message=\"$msg $(journalctl | grep hex | grep took | tail -1)\""
            return 1
        else
            msg="Starting cluster"
            echo -n "$space_filler">$(hex_sdk GetKernelConsoleDevices) ; echo -n "$msg" $'\r' | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)
            hex_sdk influx_event "${query},severity=\"I\" message=\"$msg\""
            bash -c "hex_sdk -v cube_cluster_start | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)"
            cubectl node exec -pn "rm -f /tmp/health_*error.count"
            iptables-save > /run/iptables
            return 0
        fi
    fi
}

RollingEvacuateAndReboot()
{
    # auto rolling evac and reboot in ppu update
    local inst_type=$(hex_sdk firmware_get_info $(hex_sdk firmware_get_active) | grep "install_type" | cut -d"=" -f2 | xargs)
    local cluster_info=/store/ppu/cluster-info.json
    local upgrading=false
    local last_n=$(cat $cluster_info 2>/dev/null | jq -r .[].hostname | tail -1)
    local query="insert system,category=RUG,severity=I,key=RUG00001I,service=rolling_upgrade,host=$HOSTNAME,metadata\"rolling upgrade to $(hex_cli -c firmware list | grep -i active | cut -d' ' -f2)\""
    if [ -e "$cluster_info" -a "x$inst_type" = "xPPU" ] ; then
        for N in $(cat $cluster_info | jq -r .[].hostname) ; do
            # Cube dashboard topN misses partial info after rolling upgrades
            if [ "x$last_n" = "x$T_net_hostname" ] ; then
                hex_cli -c cluster repair kafka
            fi

            if [ "x$prev_n" = "x$T_net_hostname" ] ; then
                n_role=$(cat $cluster_info | jq -r ".[] | select(.hostname == \"$N\") | .role")
                n_ip=$(cat $cluster_info | jq -r ".[] | select(.hostname == \"$N\") | .ip.management")
                n_nextactive=$(( `timeout 5 hex_sdk remote_run $n_ip "grub2-editenv list | grep next_entry | cut -d'=' -f2"` + 1 ))
                n_lastboot="$(timeout 5 hex_sdk remote_run $n_ip hex_sdk firmware_get_info $n_nextactive | grep last_boot)"
                n_fwver="$(timeout 5 hex_sdk remote_run $n_ip hex_sdk firmware_get_info $n_nextactive | grep firmware_version)"
                fwver="$(hex_sdk firmware_get_info `hex_sdk firmware_get_active` | grep firmware_version)"
                if [ "x$n_lastboot" = "xlast_boot = Never" -a "x$n_fwver" = "x$fwver" ] ; then
                    upgrading=true
                    if [ "x$n_role" = "xcontrol-converged" -o "x$n_role" = "xedge-core" -o "x$n_role" = "xcompute" ] ; then
                        hex_cli -c cluster check_repair
                        msg="Evacuating VMs on $N"
                        echo -n "$space_filler">$(hex_sdk GetKernelConsoleDevices) ; echo -n "$msg" $'\r' | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)
                        hex_sdk influx_event "${query},severity=\"I\" message=\"$msg\""
                        if ! hex_sdk remote_run $MASTER_CONTROL "hex_sdk os_pre_failure_host_evacuation_sequential $N" upgrade ; then
                            msg="Auto rolling upgrade aborted due to evacuation failures on $N"
                            echo -n "$space_filler">$(hex_sdk GetKernelConsoleDevices) ; echo -n "$msg" $'\r' | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)
                            hex_sdk influx_event "${query},severity=\"W\" message=\"$msg\""
                            break
                        fi
                    fi
                    if [ "x$(hex_sdk -f json health_vip_report | jq -r .description | cut -d '@' -f2)" = "x$N" ] ; then
                        msg="Moving VIP away from $N"
                        echo -n "$space_filler">$(hex_sdk GetKernelConsoleDevices) ; echo -n "$msg" $'\r' | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)
                        hex_sdk influx_event "${query},severity=\"I\" message=\"$msg\""
                        pcs resource cleanup
                        pcs resource move vip
                        for i in {1..10} ; do
                            new_vip=$(hex_sdk -f json health_vip_report | jq -r .description | cut -d '@' -f2)
                            if cubectl node list -j | jq -r .[].hostname | grep "^${new_vip:-NOVIP}$" && [ "x$new_vip" != "x$N" ] ; then
                                msg="Moved VIP away from $N"
                                echo -n "$space_filler">$(hex_sdk GetKernelConsoleDevices) ; echo -n "$msg" $'\r' | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)
                                hex_sdk influx_event "${query},severity=\"I\" message=\"$msg\""
                                break
                            else
                                sleep 10
                            fi
                        done
                    fi
                    msg="Rebooting $N"
                    echo -n "$space_filler">$(hex_sdk GetKernelConsoleDevices) ; echo -n "$msg" $'\r' | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)
                    hex_sdk influx_event "${query},severity=\"I\" message=\"$msg\""
                    hex_sdk remote_run $n_ip "echo YES | hex_cli -c reboot"
                    break
                fi
            fi
            prev_n=$N
        done
        hex_sdk os_nova_instance_hardreboot $(hex_sdk os_nova_list ID STATUS POWERSTATE | grep -i -e error -e nostate | cut -d" " -f1)
    fi
    if [ "x$upgrading" = "xfalse" ]; then
        if hex_sdk cube_cluster_ready ; then
            msg="Cluster checking and repairing"
            echo -n "$space_filler">$(hex_sdk GetKernelConsoleDevices) ; echo -n "$msg" $'\r' | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)
            hex_sdk influx_event "${query},severity=\"I\" message=\"$msg\""
            hex_cli -c cluster check_repair
            if hex_cli -c cluster check Storage | grep -i " ok " ; then
                rsync -ar /var/lib/ceph /store/
            fi
            msg="Cluster checked and repaired"
            echo -n "$space_filler">$(hex_sdk GetKernelConsoleDevices) ; echo -n "$msg" $'\r' | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)
            hex_sdk influx_event "${query},severity=\"I\" message=\"$msg\""
            need_be_active_servers="$(cat /mnt/cephfs/nova/instances/active_running 2>/dev/null)"
            if [ "x$need_be_active_servers" != "x" ] ; then
                for i in $need_be_active_servers ; do
                    if hex_sdk os_nova_list id status powerstate |  grep -i "$i active running" ; then
                        continue
                    else
                        hex_sdk os_nova_instance_reset $i
                        hex_sdk os_nova_instance_hardreboot $i
                        msg="Reset and booted non-active server: $i"
                        echo -n "$space_filler">$(hex_sdk GetKernelConsoleDevices) ; echo -n "$msg" $'\r' | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)
                        hex_sdk influx_event "${query},severity=\"I\" message=\"$msg\""
                    fi
                done
            fi
        else
            msg="Cluster check and repair skipped as not all nodes are bootstrapped and synced"
            echo -n "$space_filler">$(hex_sdk GetKernelConsoleDevices) ; echo -n "$msg" $'\r' | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)
            hex_sdk influx_event "${query},severity=\"I\" message=\"$msg\""
        fi
    fi
}

[ -e $BOOTSTRAP_CUBE_MODE ] || touch $BOOTSTRAP_CUBE_MODE
export CLUSTER_SIZE=$(cubectl node list | wc -l)

if [ -e /etc/appliance/state/configured -a "x$HOSTNAME" != "xunconfigured" ] ; then
    echo -n "                                                                    " $'\r' | tee $(hex_sdk GetKernelConsoleDevices)
    if grep -q manual $BOOTSTRAP_CUBE_MODE ; then
        msg="Auto bootstrap is disabled"
        echo -n "$space_filler">$(hex_sdk GetKernelConsoleDevices) ; echo -n "$msg" $'\r' | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)
        hex_sdk influx_event "${query},severity=\"I\" message=\"$msg\""
    else
        if [ "x$MASTER_CONTROL" = "x$T_net_hostname" ] ; then
            if [ $(hex_sdk -v -f none health_bootstrap_report | grep ready | wc -l) -eq 0 -o $CLUSTER_SIZE -eq 0 ] ; then
                echo "YES" | hex_cli -c cluster stop
            fi
            BootstrapAndClusterstart && RollingEvacuateAndReboot
        elif [ "x$T_cubesys_role" = "xcontrol" -o "x$T_cubesys_role" = "xcontrol-converged" -o "x$T_cubesys_role" = "xedge-core" -o "x$T_cubesys_role" = "xmoderator" ] ; then
            if [ $(hex_sdk -v -f none health_bootstrap_report | grep ready | wc -l) -eq 0 -o $CLUSTER_SIZE -eq 0 ] ; then
                echo "YES" | hex_cli -c cluster stop
            fi
            (
                cnt=0
                while ! hex_sdk remote_run ${MASTER_CONTROL:-NOMASTER} stat $BOOTSTRAP_CUBE_MARKER >/dev/null 2>&1 ; do
                    msg="Waiting for master control to finish bootstrapping [$cnt min]"
                    echo -n "$space_filler">$(hex_sdk GetKernelConsoleDevices) ; echo -n "$msg" $'\r' | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)
                    hex_sdk influx_event "${query} code=0,status=\"$msg\""
                    ((cnt++))
                    sleep 60
                done
                BootstrapAndClusterstart && RollingEvacuateAndReboot
                :> $BOOTSTRAP_CUBE_MODE
            )&
            echo $! > $BOOTSTRAP_CUBE_MODE
        else
            (
                cnt=0
                while ! cubectl node exec -r control stat $BOOTSTRAP_CUBE_MARKER >/dev/null 2>1 ; do
                    msg="Waiting for control(s) to finish bootstrapping [$cnt min]"
                    echo -n "$space_filler">$(hex_sdk GetKernelConsoleDevices) ; echo -n "$msg" $'\r' | tee $BOOTSTRAP_CUBE_LOG $(hex_sdk GetKernelConsoleDevices)
                    hex_sdk influx_event "${query},severity=\"I\" message=\"$msg\""
                    ((cnt++))
                    sleep 60
                done
                BootstrapAndClusterstart && RollingEvacuateAndReboot
                :> $BOOTSTRAP_CUBE_MODE
            )&
            echo $! > $BOOTSTRAP_CUBE_MODE
        fi
    fi
fi
