name: Fast Forward Merge

on:
  pull_request_target:
    types:
      - labeled

permissions:
  contents: read

jobs:
  merge:
    permissions:
      contents: write  # for Git to git push
    if: ${{ github.event.label.name == 'done' && github.event.pull_request.mergeable == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Check Out PR Target Branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Merge
        env: 
          TOPIC_BRANCH: ${{ github.head_ref }}
        run: |
          git pull origin $TOPIC_BRANCH
          git checkout $TOPIC_BRANCH
          git checkout @{-1}
          git branch
          git merge --ff-only $TOPIC_BRANCH
          git push
